application: lightupleeton
version: 1-1-0
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: "2.6"
- name: webob
  version: "1.2.3"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /css
  static_dir: static/css
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /img
  static_dir: static/img
  secure: always

- url: /api/.*
  script: endpoints.api
  secure: always

# - url: /cron/.*
#   script: endpoints.cron

- url: .*
  script: endpoints.app
  secure: always
