application: lightupleeton
version: 1-1-0
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: "2.6"
- name: webob
  version: "1.2.3"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /css
  static_dir: static/css
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /img
  static_dir: static/img
  secure: always

- url: /api/.*
  script: endpoints.api
  secure: always

- url: /cron/.*
  script: endpoints.cron
  login: admin

- url: .*
  script: endpoints.web
  secure: always

env_variables:
  GOOGLE_MAPS_PROD: AIzaSyDej8MbNNc58ByNeoxmOAHavPADP4_werc
  GOOGLE_MAPS_DEVEL: AIzaSyD-NyV_El4O2p54jlFyroK7k3BIv7flZRU
