application: lightupleeton
version: 1-0-1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: "2.6"
- name: webob
  version: "1.2.3"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /api/.*
  script: endpoints.api

# - url: /cron/.*
#   script: endpoints.cron

- url: .*
  script: endpoints.app
