application: lightupleeton
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js
  
- url: /img
  static_dir: static/img

- url: /api/.*
  script: lul.rest.api
  
- url: /manage
  login: required
  script: lul.app
  
- url: .*
  script: lul.app
